---
title: "Variables aleatorias y distribuciones de probabilidad"
description: "."
execute:
  echo: true
  warning: false
---

## Espacios, eventos y distribuciones de probabilidad.

### Definiciones
Imaginemos un ejemplo de algo que facilmente reconoceremos como aleatorio: un dado. Cuando tiramos un dado, el resultado estará dado por el número que aparece en la cara que queda hacia arriba, de 1 al 6 en un dado tradicional. 
Si tenemos dos dados diferentes (digamos, uno rojo y uno azul) entonces tenemos 36 diferentes resultados posibles, pero si lo que estamos observando es la suma de ambos, las posibilidades sólo son 12. 

Para poder describir este tipo de fenómenos, necesitamos aclarar algunos conceptos. Dado que en algunas ocasiones trabajaremos con un sólo objeto, como en el caso de un dado, y otras trabajaremos con varios, como cuando observamos los átomos de un gas, definimos el *sistema* como aquello que estamos intentando describir. A las variables relevantes del sistema, como el valor de cada uno de los dados que tiramos, o la posición y velocidad de todos nuestros átomos, las agruparemos en un vector, que describirá un *estado* del sistema. Normalmente denotaremos este vector como $\sigma$. Así mismo, podemos ver que las componentes de $\sigma$ pueden ser discretas, como en el caso de los dados, o continuas, como en el caso de los átomos del gas. Incluso podríamos pensar en casos en que el estado sea una mezcla de variables continuas y discretas, como si en el caso del gas, además de las posiciones y velocidades, incluyeramos la configuración electrónica de cada átomo. 


Partiendo del concepto del estado de un sistema, podemos definir un espacio $\Omega$ a partir de todas las posibles observaciones del estado $\sigma$. En el caso de un dado, $\Omega=\{1,2,3,4,5,6\}$, mientras que en el caso de un gas de partículas $\Omega$ es el espacio de fase.
El espacio $\Omega$ entonces se compone de todos los posibles valores que puede tomar el estado, y a estos elementos les llamaremos *eventos*, y los denotaremos $\omega \in \Omega$.
Un evento entones podría al tirar nuestro dado, caiga un 6, o que nuestro par de dados caiga en $\sigma=(3,4)$.

Finalmente, $\Omega$ es un conjunto especial de eventos, que consiste en todos los resultados posibles, pero de la misma manera podemos definir otros conjuntos. Por ejemplo, podemos definir un conjunto compuesto por todos los eventos en que el valor del dado sea mayor que 3. Este conjunto lo escribiríamos como $A = \left\{4,5,6\right\}$. Y así como tenemos el conjunto especial, $\Omega$, que contiene todos los posibles eventos, existe otro conjunto especial, que es el conjunto vacío, es decir, el que no contiene ningún evento $\emptyset=\{\}$. 


### Los axiomas de la probabilidad
Las definiciones discutidas hasta ahora pueden parecer rebuscadas, pero nos permiten definir la probabilidad de manera axiomátia. En este enfoque, definimos una una función de medida que mapea un conjunto de eventos $A$ a un número real que cumple con los siguientes axiomas (conocidos como los axiomas de Kolmogorov):

1. $P(A)\geq 0$ para cualquier conjunto $A$,

   Esto quiere decir que no podemos tener probabilidades negativas.

2. $P(\Omega)=1$,

   La probabilidad de que ocurra cualquier evento es 1. Es decir, el resultado de nuestra observación debe encontrarse en el espacio $\Omega$ con absoluta certeza.

3. Supongamos que tenemos una colección (finita o infinita, pero contable) de conjuntos $A_i$ (donde $i=1,2,3,4,...$). Si estos conjuntos son mutuamente excluyentes, de forma que:
   $$A_i\cap A_j = ∅ \textrm{ para todo } i\neq j$$
   entonces
   $$P(\cup_i A_i) = \sum_i P(A_i)$$

   Este axioma es un poco dificil de visualizar, entonces podemos valernos de nuestro ejemplo del dado. Si tomamos dos posibles resultados, digamos 3 y 4, entonces nuestros conjuntos de eventos serían $A_1 = \{3\}$ y $A_2 = \{4\}$. La intersección $A_1 \cap A_2 = \emptyset$ porque ningún elemento de $A_1$ se encuentra en $A_2$. La probabilidad de la unión de ambos conjuntos es la probabilidad de que el dado caiga en 3 o en 4, y el axioma nos diría que $P(\{3,4\}) = P(\{3\})+P(\{4\})$. Por otro lado, si imaginamos dos conjuntos $A_1 = \{3, 4\}$ y $A_2 = \{4, 5\}$, entonces la probabilidad de la unión de ambos sería $P(\{3,4,5\}) \neq P(\{3,4\}) + P(\{4,5\})$ por que estaríamos sumando dos veces $P(\{4\})$. 

Existen dos propiedades más de una distribución que pueden ser derivadas a partir de los axiomas:

4. Si el conjunto $\bar{A}$ es el complemento de $A$, eso quiere decir que $A\cap\bar{A} = \Omega$ y que $A\cup\bar{A} = \emptyset$. Por el axioma 3, $P(\Omega)=P(A\cap\bar{A})=P(A)+P(\bar{A}) = 1$. Si despejamos, obtenemos: 
   $$P(\bar{A}) = 1-P(A)$$
5. Usando este resultado, y considerando que $\bar{\Omega} = \emptyset$, podemos ver que $$P(\emptyset) = 1-P(\Omega)=0$$. 

A la función $P(A)$ le llamaremos una distribución de probabilidad. 

Aquí podemos hacer un parentesis para mencionar que si se define una colección de conjuntos $\mathcal{F} = \{A_1, A_2, ...\}$ de forma cerrada, es decir, que se cumplan las siguientes condiciones: 

* $\emptyset\in\mathcal{F}$ y $\Omega\in\mathcal{F}$,

* Si $A\in\mathcal{F}$ entonces $\bar{A}\in\mathcal{F}$,

* Si $A_i \in\mathcal{F}$ y  $A_j \in \mathcal{F}$ entonces $A_i\cap A_j\in\mathcal{F}$.

entonces se le puede llamar a $\mathcal{F}$ un $\sigma$-ágebra y se puede definir un espacio de probabilidades como $(\Omega, \mathcal{F}, P)$. Estos detalles son fundamentales para definir una teoría de la probabilidad, pero quedan fuera del alcance de este curso. 

Finalmente es importante conectar esta definición formal con nuestro objeto de estudio. Es decir, hasta ahora, definimos la distribución de probabilidad como una función que conecta conjuntos en un espacio con un número real. Sin embargo, la conexión entre esta función y algún efecto medible en un sistema aleatorio no está explícita aunque solemos tener una idea intuitiva de lo que representa la probabilidad. Esta conexión esta dada por la ley de los números grandes, que dice que si observamos nuestro sistema $N$ veces y contamos $N_A$ como la cantidad de veces que observaremos un evento que pertenece a un conjunto $A$, en el límite en que $N$ tiende a infinito, obtendremos: 
$$N_A = \lim_{N\rightarrow\infty} N P(A)$${#eq-large-numbers}

### Distribuciones de probabilidad continuas

Hasta ahorita los ejemplos que hemos descrito, y la forma en que hemos pensado en los conjuntos es más acorde a sistemas discretos, pero existen muchos sistemas que requieren una descripción usando variables en un espacio continuo. Anteriormente mencionamos por ejemplo, un gas de átomos, donde las variables son velocidad y posición de todos los átomos. Otro ejemplo común es el de la altura de una persona elejida al azar en una población. 

Una de las ventajas de la definición que hicimos de la probabilidad como una medida que se aplica a un conjunto, es que es fácil generalizarla a un espacio continuo. Observando los axiomas, podríamos definir directamente conjuntos de eventos, como por ejemplo, que la altura de una persona sea exáctamente 1.70m. Sin embargo, esto causa un problema, porque se pueden definir un número infinito no contable de conjuntos de esta forma, y por más pequeña que fuera la probabilidad de encontrar esa altura específica, la suma de un número incontable de números es infinita, sin importar cuan pequeños sean esos números. Esto significa que la probabilidad de encontrar a alguien que mida exáctamente 1.70m tiene que ser 0. 

El truco es que podemos dividir el espacio en $N$ conjuntos de tamaño $\delta$, y hacer que $N\rightarrow \infty$. Haciendo esto, podemos asociar una probabilidad al conjunto de eventos en donde la altura se encuentra dentro de cierta vecindad.  

## Distribuciones conjuntas y distribuciones condicionales

### Distribuciones de probabilidad conjunta

En la discusión del tercer axioma hablamos sobre la probabilidad de que un evento pertenezca a la unión de varios conjuntos mutuamente excluyentes. 
Si dos conjuntos $A$ y $B$ no son mutuamente excluyentes, entonces existe una intersección entre ambos conjuntos; es decir, se puede escribir $A\cap B \neq \emptyset$. A la probabilidad de que un evento $\omega$, pertenezca a ambos conjuntos, $(\omega\in A) \land (\omega\in B)$, la escribiremos como:
$$P(A\cap B)$$ 
y la llamamos la probabilidad conjunta. 

Esta probabilidad es útil, por ejemplo, para describir el caso en que tenemos dos dados. En este caso, podríamos definir el conjunto $A$ a partir de todos los eventos en los que el dado $d_A = 2$ y el conjunto $B$ como todos los eventos en los que el dado $d_B = 4$. Si $d_A = 2$ y $d_B = 3$, nuestro evento pertenece a $A$, pero no a $B$. Para que pertenezca a ambos conjuntos, tenemos que tener el resultado específico de $d_A = 2$ y $d_B=4$. 

Imaginemos que dividios el espacio $\Omega$ en una colección de conjuntos mutuamente excluyentes $B_i$. Esto quiere decir que: 

* $$\cup_i B_i = \Omega$$

* $$B_i \cap B_j = \emptyset $$ para todo par $i\neq j$

Como esta colleccion cumple con las condiciones del axioma 3, entonces podemos decir que $P(\cup_i B_i) = \sum_i P(B_i) = 1$. Es decir, como subdividimos todo el espacio en los conjuntos $B_i$, podemos asegurar que nuestro evento debe pertenecer a algún conjunto $B_i$. 

Pero además, podemos ver que, si $B_i\cap B_j = \emptyset$, entonces $(A\cap B_i)\cap(A\cap B_i) = \emptyset$, lo que significa que todos los conjuntos $A\cap B_i$ cumplen también con las condiciones del axioma 3, y por lo tanto:

$$
\begin{align}
\sum_i P(A \cap B_i)&= P(\cup_i (A\cap B_i))\\
&= P(A \cap (\cup_i B_i))\\
&= P(A \cap \Omega) \\
&= P(A)
\end{align}
$$ 
De nuevo, podemos visualizar mejor lo que significa este resultado si recordamos nuestros dos dados. En este caso, podemos pensar que nuestro conjunto $A$ contiene los eventos en los que $d_A = 3$, y el conjunto $B_i$ contiene los eventos en que $d_B = i$. La colección de los conjuntos $B_i$ entonces cubre todo el espacio, por que si el evento cumple con $d_B = 1$, este evento pertenece a $B_1$, si $d_B=2$, pertenece a $B_2$ y así para todos los valores posibles de $d_2$. 

Del lado izquierdo de la expresión, tenemos la suma de todas las probabilidades conjuntas. Eso sería, la probabilidad $P(A \cup B_1)+P(A \cup B_2) ...$, es decir, la probabilidad de que $d_A = 3$ y $d_B = 1$ más la probabilidad de que $d_A = 3$ y $d_B = 2$ más la probabilidad de que $d_A=3$ y $d_B = 3$, etc. Lo que el resultado anterior nos dice, es que esta probabilidad es igual a la probabilidad $P(A)$, es decir, la probabilidad de que $d_A = 3$. Lo podemos imaginar como que estamos integrando la probabilidad de todos los posibles valores de $d_B$ y recuperando la probabilidad de $d_A = 3$. A la probabilidad $P(A)$ recuperada a partir de las probabilidades conjuntas $P(A\cup B_i)$ le llamamos la *probabilidad marginal*

Este resultado se puede generalizar y escribir de la forma: 
$$
\sum_iP(A_i\cap B_j\cap C_k \cap ...) = P(B_j \cap C_k \cap ...)
$${#eq-setintegration}

### Distribuciones de probabilidad condicional

En algunas ocasiones querremos saber cual es la probabilidad de que algo ocurra dada una información. El ejemplo de los dados en este caso es menos útil, por que ambos dados son independientes (aunque se pueden construir ejemplos a partir de operaciones entre ambos dados). En vez de eso, podemos pensar en un mazo de cartas, que normalmente tiene 52 cartas, con 13 números de cada palo y cuatro palos. En este caso, la pregunta sería la siguiente: Si sabemos que sacamos una carta con un número mayor que 10 (sota, reina o rey), ¿Cual es la probabilidad de que sea de corazones?

La probabilidad condicional está dada por la expresión: 
$$P(A|B) = \frac{P(A\cap B)}{P(B)}$${#eq-conditionalprob}
En nuestro ejemplo, supondremos que el conjunto $B$ en este caso consiste en los eventos en que sacamos una carta mayor que 10. Sabemos que hay en total 12 cartas mayores que 10 (tres por palo), entonces la probabilidad $P(B) = \frac{12}{52}$. Si $A$ es el conjunto de los eventos en que sacamos un corazón, y hay tres corazones mayores que 10, entonces, la probabilidad $P(A\cap B) = \frac{3}{52}$. Utilizando la expresión anterior vemos que la probabilidad de sacar corazones, dado que sabemos que sacamos una carta mayor a 10 está dada por:
$$P(A|B)= \frac{\frac{3}{52}}{\frac{12}{52}} = \frac{1}{4}$$
Este resultado es lo que esperamos si pensamos que el número de cartas de corazon representa una cuarta parte de las cartas mayores que 10.

A partir de la ecuación @eq-setintegration, podemos escribir la siguiente expresión para la probabilidad condicional: 
$$\sum_i P(A|B_i)P(B_i) = P(A)$${#eq-totalprob}
A esta expresión se le llama la ley de la probabilidad total, y será fundamental más adelante para comprender y obtener resultados sobre procesos estocásticos. 

## Variables aleatorias y notación

Hasta ahora hemos trabajado con probabilidades que escribimos como $P(A)$ que quiere decir probabilidad de que un evento $\omega$ pertenezca al conjunto $A$. También introducimos el estado de un sistema como $\sigma$, que puede valer algo diferente cada vez que lo observamos, y el espacio de las posibles observaciones es $\Omega$. Utilizando nuestro ejemplo de los dados, si quisieramos escribir la probabilidad de que un dado salga 3, tendríamos que escribir $P(\{3\})$, en donde los corchetes indican que el conjunto que estamos evaluando es el que contiene al valor 3. En general, esto significaría escribir la probabilidad como $P({\sigma})$ para indicar que estamos evaluando la medida de probabilidad asociada al conjunto que contiene al punto $\sigma$ en el espacio de posibles eventos. En lo que sigue, escribiremos simplemente $P(\sigma)$. 

Finalmente, en algunas ocasiones es útil definir funciones a partir del estado del sistema. Dado que el sistema toma un valor diferente en sucesivas observaciones, una función $F(\sigma)$ también tomará un valor diferente. Al resultado de la función, que puede ser un valor o un vector, se le llama una variable aleatoria. Por ejemplo, si tiramos dos dados, la suma de ambos dados será una variable aleatoria. En mecánica estadística es común evaluar la energía interna de un sistema que depende de las posiciones y velocidades, es decir, del estado: $E(\sigma)$. 

Estas variables normalmente son numéricas, lo que permite obtener observables como el promedio o la varianza.
Este valor promedio surge a partir de minimizar la suma de las distancias entre las observaciones y el valor promedio, en el límite en que se realizan $N\rightarrow\infty$ observaciones.
Si tenemos una variable aleatoria $R(\sigma)$, el promedio de una variable aleatoria se define como 
$$\left<R\right> = \sum_{\sigma\in\Omega} P(\sigma) R(\sigma)$$,
donde la suma se realiza sobre todos los posibles estados del espacio $\Omega$.
En este sentido, se puede entender como una medida del centro de la distribución $P(R)$.

La varianza se define como:
$$var(R) = \left<R^2\right>-\left<R\right>^2$$
donde al término \left<R^2\right> se le llama el segundo momento y se calcula como:
$$\left<R^2\right> = \sum_{\sigma\in\Omega} P(\sigma) R(\sigma)^2$$
La varianza, así como la desviación estandar $std = \sqrt{var}$ es una medida de la dispersión entre las observaciones de una variable aleatoria, o el ancho de una distribución. 

En general, la idea de los momentos se puede generalizar de la siguiente forma. El momento $n$ está dado por: 
$$\left<R^n \right> = \sum_{\sigma\in\Omega} P(\sigma) R(\sigma)^n $$
Estos momentos son útiles como mediciones de la forma de una distribución. Por ejemplo, una distribución Gausiana está definida por sus primeros dos momentos. En general, si dos distribuciones tienen los mismos momentos, la forma de la distribución será la misma. 
